version: '3.1'

services:

  user-service-db:
    image: postgres:latest
    env_file: .env
    environment:
    - POSTGRES_DB=${DB_NAME}
    - POSTGRES_USER=${DB_USER}
    - POSTGRES_PASSWORD=${DB_PASSWORD}

  user-service:
    image: user-service:latest
    env_file: .env
    environment:
    - NODE_ENV=${NODE_ENV}
    - DB_HOST=user-service-db
    - DB_PORT=5432
    - DB_NAME=${DB_NAME}
    - DB_USER=${DB_USER}
    - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
    - user-service-db
    links:
    - user-service-db
    ports:
    - 3030:3000
